require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "public/**/*"
    - "tmp/**/*"
Style/Documentation:
  Enabled: false